"""ApiKeyModel

Revision ID: 0591983f132e
Revises: 44c6338b78c4
Create Date: 2026-02-05 14:38:56.904401

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0591983f132e"
down_revision: Union[str, Sequence[str], None] = "44c6338b78c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
