"""Fix activiry relations

Revision ID: 0f543f025606
Revises: ee5a1e96b09c
Create Date: 2026-02-03 12:32:00.357869

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f543f025606"
down_revision: Union[str, Sequence[str], None] = "ee5a1e96b09c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_double_sub_activities",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("double_sub_activity_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["double_sub_activity_id"],
            ["double_sub_activities.id"],
        ),
        sa.PrimaryKeyConstraint("company_id", "double_sub_activity_id", "id"),
    )
    op.create_index(
        op.f("ix_company_double_sub_activities_id"),
        "company_double_sub_activities",
        ["id"],
        unique=False,
    )
    op.drop_index(op.f("ix_company_activities_id"), table_name="company_activities")
    op.drop_table("company_activities")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_activities",
        sa.Column("company_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("activity_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("company_activities_activity_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("company_activities_company_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "company_id", "activity_id", "id", name=op.f("company_activities_pkey")
        ),
    )
    op.create_index(
        op.f("ix_company_activities_id"), "company_activities", ["id"], unique=False
    )
    op.drop_index(
        op.f("ix_company_double_sub_activities_id"),
        table_name="company_double_sub_activities",
    )
    op.drop_table("company_double_sub_activities")
    # ### end Alembic commands ###
