"""New struct of activities

Revision ID: 1c1412b8317d
Revises: 68efe4d7f26d
Create Date: 2026-02-03 15:59:15.720672

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c1412b8317d"
down_revision: Union[str, Sequence[str], None] = "68efe4d7f26d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_activities",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("activity_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("company_id", "activity_id", "id"),
    )
    op.create_index(
        op.f("ix_company_activities_id"), "company_activities", ["id"], unique=False
    )
    op.create_table(
        "company_sub_activities",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("sub_activity_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sub_activity_id"],
            ["sub_activities.id"],
        ),
        sa.PrimaryKeyConstraint("company_id", "sub_activity_id", "id"),
    )
    op.create_index(
        op.f("ix_company_sub_activities_id"),
        "company_sub_activities",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_company_sub_activities_id"), table_name="company_sub_activities"
    )
    op.drop_table("company_sub_activities")
    op.drop_index(op.f("ix_company_activities_id"), table_name="company_activities")
    op.drop_table("company_activities")
    # ### end Alembic commands ###
