"""Fix Company field

Revision ID: 2af3c31c6f43
Revises: 1c1412b8317d
Create Date: 2026-02-04 13:24:07.159369

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2af3c31c6f43"
down_revision: Union[str, Sequence[str], None] = "1c1412b8317d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
