"""Fix CompanyActivity lazy selectin

Revision ID: 4251d4d6b44c
Revises: c3c376382628
Create Date: 2026-02-03 11:30:54.985784

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4251d4d6b44c"
down_revision: Union[str, Sequence[str], None] = "c3c376382628"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
