"""Fix CompanyActivity field

Revision ID: 44c6338b78c4
Revises: 2af3c31c6f43
Create Date: 2026-02-04 13:25:38.806805

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "44c6338b78c4"
down_revision: Union[str, Sequence[str], None] = "2af3c31c6f43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
