"""Fix company

Revision ID: 68efe4d7f26d
Revises: 0f543f025606
Create Date: 2026-02-03 12:35:32.931369

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "68efe4d7f26d"
down_revision: Union[str, Sequence[str], None] = "0f543f025606"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
