"""CompanyActivity relationship

Revision ID: 9a73421671f2
Revises: cbd7bea54d32
Create Date: 2026-02-03 10:16:14.834434

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a73421671f2"
down_revision: Union[str, Sequence[str], None] = "cbd7bea54d32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_activities",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("activity_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("company_id", "activity_id", "id"),
    )
    op.create_index(
        op.f("ix_company_activities_id"), "company_activities", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_company_activities_id"), table_name="company_activities")
    op.drop_table("company_activities")
    # ### end Alembic commands ###
