"""Add lazy joined

Revision ID: b5c22f0f604c
Revises: 9a73421671f2
Create Date: 2026-02-03 10:32:54.786468

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "b5c22f0f604c"
down_revision: Union[str, Sequence[str], None] = "9a73421671f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
