"""Lazy selectin

Revision ID: c3c376382628
Revises: b5c22f0f604c
Create Date: 2026-02-03 10:34:52.406475

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c3c376382628"
down_revision: Union[str, Sequence[str], None] = "b5c22f0f604c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
