"""Fix lazy subactivity

Revision ID: ee5a1e96b09c
Revises: 4251d4d6b44c
Create Date: 2026-02-03 11:34:21.528242

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "ee5a1e96b09c"
down_revision: Union[str, Sequence[str], None] = "4251d4d6b44c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
